# drop procedure

DROP PROCEDURE BasicFilter;

# create procedure
DELIMITER //
CREATE PROCEDURE BasicFilter()
BEGIN
DROP TABLE IF EXISTS RESULT_BASICFILTER;
CREATE TABLE RESULT_BASICFILTER AS
SELECT CODE,NAME,INDUSTRY,PE,ESP,BVPS,PB,UNDP,PERUNDP,REV,PROFIT,GPR,NPR FROM basic_info 
WHERE (CODE LIKE '600%' OR CODE LIKE '601%' OR CODE LIKE '603%' OR CODE LIKE '00%')
AND PE > 1 AND PE < 150
AND PB > 1 AND PB < 4
AND ESP > 0.1
AND GPR > 10
AND NPR > 10
AND REV > 10
AND PROFIT > REV;
END;


# call procedure
CALL BasicFilter();
