SELECT T1.CODE,T1.PRICE,T2.PRICE AS AVG_PRICE,T1.* FROM RESULT_ALLSTOCKINDEX AS T1
INNER JOIN RESULT_ALLINDEX_AVG AS T2
ON T1.INDUSTRY = T2.INDUSTRY
WHERE 1 = 1
AND T1.GPR >= T2.GPR
AND T1.MBRG >= T2.MBRG
AND T1.EPSG >= T2.EPSG
AND T1.SEG >= T2.SEG
AND T1.CASHFLOWRATIO >= T2.CASHFLOWRATIO
AND T1.EPS >= T2.EPS
